### ISSUE TITLE
Doesn't work on all site such as the invaluable Notion - likely an easy fix that will make thousands of users extremely happy!

### ISSUE THREAD

**Issue by binvius** [JSchmiegel/DeepLineBreaks#3]
Hi Blake,
 As a very long-term Firefox power-user, I believe your extension is one of the most useful ever made and as a result, recommend it to everyone that will listen.

You've done such a fantastic job, I simply cannot thank you enough for the huge impact you are having!

I heavily rely on it for my plans to make the world a better place for humanity so it is frustrating that it doesn't work well in Notion.com (Notion.so) - one of the main sites we use throughout the day.

As you seem like a highly-skilled dev, I was just wondering if you may be kind enough to spare a few seconds investigating if it is an easy fix.

To make things as easy as possible for you, I have created a sample page where you can test your efforts:

https://olympuse.notion.site/olympuse/Troubleshooting-Firefox-extension-Find-Replace-for-Text-Editing-by-Blake-Altice-02da5e8f9bb44e7cad5b826086da4ae7

Please do not hesitate to contact me if I can be of any further assistance in helping rectify this issue.

Massive thanks in advance if you can spare a few seconds to take a look.

Warm regards,

Binvius

**Comment by JSchmiegel** [comment]
Hi Binvius,

Sorry, but you created the issue in the wrong repository. I am not Blake, and I didn't create the ["Find & Replace for Text Editing"-Add-on](https://addons.mozilla.org/en-US/firefox/addon/find-replace-for-text-editing/). I'll close this issue here.

Unfortunately, I was not able to find a repo of [Blake Altice](https://addons.mozilla.org/en-US/firefox/user/16160279/). Maybe you contact him via his [website](https://find-and-replace-f6588.firebaseapp.com/).

Best regards
Jonas

**Comment by binvius** [comment]
Jonas - I am deeply sorry about that.

Thanks for your kind links.

Hope you have a lovely day.
